### PR TITLE
A work in progress to port sublime_tortoise to Sublime Text 3

### PR DESCRIPTION
**Pull request by asfaltboy**
Seems to work ok so far, please review and test if able

### CODE REVIEW

**Comment by atwright147** [comment]
Hi,

I have two questions:
1. Is this still backwards compatible with ST2?
2. Would you like to take ownership of this project (I'm not a Python dev, so cannot curate it as well as it deserves).

Cheers, Andy

**Comment by asfaltboy** [comment]
1. I don't believe it is... hence it's on it's own branch on my repo. Not
   sure how to make a pull request with a directive for a new branch to be
   created.
2. I'd love that, have a few issues with that though:

a. as you can probably see from my late response, these days it's rare for
me to find time to contribute to projects on github...

b. I'm not sure how to allow people use (and can contribute to) this fork
rather than the original one by @wbond. Seeing that the original has not
been updated in 2 years, I'd like to see this fork become the main one.
Could we maybe rename the fork to TortoiseX or something and submit it back
to http://wbond.net/sublime_packages/community?

.,:/_Ethernet (n): something used to catch the etherbunny_:,.

**Comment by westy** [comment]
Thought would chip in with what I think the priorities should be.
1) Get in package control, just makes the whole installation/update process easy.
2) I see a lot of talk of git, but please ensure TortoiseHg support is still there.

**Comment by tmuka** [comment]
thanks, these changes got me working again!  i did have to uncomment the svn and git paths in your modified Tortoise.sublime-settings file.  I appreciate your work on this.  

edit. fwiw, i only tested with tortoiseSVN.  I'm okay with the name changing or not in package control, it doesn't matter to me as long as I can get it somewhere, git, etc.

**Comment by asfaltboy** [comment]
OK guys, thanks for the feedback, ST2 should be supported with the latest commit, and the package should be installable from package control using the git report (on ST3).

@westy:
1) I think we will be able to get the existing Tortoise plugin to support it, discussion @ wbond#25
2) TortoiseHG should continue to work as usual (unless we missed something). Please go ahead and check latest commit, and your findings.

**Comment by asfaltboy** [comment]
@tmuka: Hmmm, do you have non-standard svn and git paths? The code should have detected the executable paths in those locations...

**Comment by tmuka** [comment]
No, my tortoise paths should be standard (they match the commented out
lines)...

**Comment by asfaltboy** [comment]
Please open a separate issue with:
a. the action you attempted
b. the details of the error you received.
c. the paths (or configuration names) that weren't automatically detected - i.e: the ones you had to configure manually.

**Comment by asfaltboy** [comment]
Can anyone (who is still using sublime text 2) please test the branch for stability?

**Comment by westy** [comment]
Sorry, but will attempt to raise this thread from the dead :)

I'm trying ST3 again, and loving what I'm seeing - the boost to performance and the indexing features are superb.

I really want this plugin to work though!
So, I thought I'd have another look...

I have cloned the repo into Data\Packages\Tortoise.
When I load Sublime I get this in the console:

> reloading plugin Tortoise.Tortoise
> Traceback (most recent call last):
>   File "C:\Cloud Sync\OneDrive\Portable Software\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
>     m = importlib.import_module(modulename)
>   File "./python3.3/importlib/__init__.py", line 90, in import_module
>   File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
>   File "<frozen importlib._bootstrap>", line 1022, in load_module
>   File "<frozen importlib._bootstrap>", line 1003, in load_module
>   File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
>   File "<frozen importlib._bootstrap>", line 853, in _load_module
>   File "<frozen importlib._bootstrap>", line 980, in get_code
>   File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
>   File "C:\Cloud Sync\OneDrive\Portable Software\Sublime Text 3\Data\Packages\Tortoise\Tortoise.py", line 63
>     except (NotFoundError) as (exception):
>                               ^
> SyntaxError: invalid syntax

Any pointers for what to look at?
I'm guessing that one of the imports listed in Tortoise.py is either no longer needed, or out of date?

I'm running an old version of TortoiseHg too (1.1.7), in case that's a factor.
I'd hope the plugin would load though, and just bork when trying to run a command.
Perhaps there's some config I need to set?

I'll keep looking, but thought would post here in case anyone can help.

Cheers,
Westy

**Comment by westy** [comment]
I have tweaked my sublime-settings to contain the following (in case it helps):

> {
>     // The path to the TortoiseHg thgw.exe (or hgtk.exe) executable
>     "hg_hgtk_path": "C:\\Program Files (x86)\\TortoiseHg\\hgtk.exe"
> 
>     // If debug messages should be printed to the console
>     "debug": true,
> 
>     // Use workbench instead of log (TortoiseHg >= 2.0)
>     "use_workbench": false
> }

Still same erorr on load though :/

**Comment by westy** [comment]
More progress - I think I may have to fork myself....

Corrected some syntax issues with the code. Obviously out of date I guess - apologies, I'm no Python programmer.

He's the Diff:
```
 Tortoise.py | 21 +++++++++++----------
 1 file changed, 11 insertions(+), 10 deletions(-)

diff --git a/Tortoise.py b/Tortoise.py
index 6926257..da1189c 100644
--- a/Tortoise.py
+++ b/Tortoise.py
@@ -32,17 +32,17 @@ class TortoiseCommand():
 
         try:
             vcs = TortoiseSVN(settings.get('svn_tortoiseproc_path'), path)
-        except (RepositoryNotFoundError):
+        except RepositoryNotFoundError:
             pass
 
         try:
             vcs = TortoiseGit(settings.get('git_tortoiseproc_path'), path)
-        except (RepositoryNotFoundError):
+        except RepositoryNotFoundError:
             pass
 
         try:
             vcs = TortoiseHg(settings.get('hg_hgtk_path'), path)
-        except (RepositoryNotFoundError):
+        except RepositoryNotFoundError:
             pass
 
         if vcs == None:
@@ -60,7 +60,7 @@ def handles_not_found(fn):
     def handler(self, *args, **kwargs):
         try:
             fn(self, *args, **kwargs)
-        except (NotFoundError) as (exception):
+        except NotFoundError as exception:
             sublime.error_message('Tortoise: ' + str(exception))
     return handler
 
@@ -72,7 +72,7 @@ def invisible_when_not_found(fn):
             if res != None:
                 return res
             return True
-        except (NotFoundError):
+        except NotFoundError:
             return False
     return handler
 
@@ -359,7 +359,7 @@ class Tortoise():
         if path in file_status_cache and file_status_cache[path]['time'] > \
                 time.time() - settings.get('cache_length'):
             if settings.get('debug'):
-                print 'Fetching cached status for %s' % path
+                print('Fetching cached status for %s', path);
             return file_status_cache[path]['status']
 
         if settings.get('debug'):
@@ -367,7 +367,7 @@ class Tortoise():
 
         try:
             status = vcs.check_status(path)
-        except (Exception) as (exception):
+        except Exception as exception:
             sublime.error_message(str(exception))
 
         file_status_cache[path] = {
@@ -376,8 +376,9 @@ class Tortoise():
         }
 
         if settings.get('debug'):
-            print 'Fetching status for %s in %s seconds' % (path,
-                str(time.time() - start_time))
+            print('Fetching status for %s in %s seconds',
+                  path,
+                  str(time.time() - start_time));
 
         return status
 
@@ -482,7 +483,7 @@ class TortoiseHg(Tortoise):
             try:
                 self.set_binary_path('TortoiseHg\\thgw.exe',
                     'thgw.exe', 'hg_hgtk_path')
-            except (NotFoundError):
+            except NotFoundError:
                 self.set_binary_path('TortoiseHg\\hgtk.exe',
                     'thgw.exe (for TortoiseHg v2.x) or hgtk.exe (for ' +
                     'TortoiseHg v1.x)', 'hg_hgtk_path')

```

What I'm seeing now is:
```
error: Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages\User\Tortoise.sublime-settings:7:5
error: expected bytes, bytearray or buffer compatible object
```

I feel like I may be getting somewhere though :)

**Comment by westy** [comment]
Ah, was a error in my sublime-settings file.

Still getting:
error: expected bytes, bytearray or buffer compatible object

But looks like debug messages are working, and it's calling hg!

Going to fork, I'll continue spamming there.

**Comment by atwright147** [comment]
@westy I have switched to VSCode, in my opinion it is way better than Sublime Text and actually gets updated. It also natively contains Git integration.

**Pull request closed without merging**
